# Generated by Django 3.1.12 on 2021-07-22 07:50

import ad.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='ads/pics')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('NORMAL', 'Normal'), ('COMPANY', 'Company'), ('CAR', 'Car')], default='NORMAL', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('address', models.TextField(default='')),
                ('location', models.JSONField(default=ad.models.default_location)),
                ('images', models.ManyToManyField(blank=True, to='ad.Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
