# Generated by Django 3.1.12 on 2021-07-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_ad_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
