# Generated by Django 3.1.12 on 2021-07-26 17:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('seller', 'buyer')},
        ),
        migrations.RemoveField(
            model_name='chat',
            name='ad',
        ),
    ]
